server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
  thymeleaf:
    cache: false
application:
  vault-secret-path: basic-secret-stg
  vault-role: basic-secret-role-skiresorts-stage