server:
  port: 8081
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${secret.postgres.url}
    username: ${secret.postgres.username}
    password: ${secret.postgres.password}
  thymeleaf:
    cache: false
devtools:
  livereload:
    enabled: true

